name: bioreino_mobile
description: Plataforma de cursos online de biologia.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  google_fonts: 
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  mongo_dart: ^0.9.1
  realm: ^1.0.3
  shared_preferences: ^2.1.1
  flutter_cache_manager: ^3.3.0
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  min_sdk_android: 19
  image_path: "assets/launcher/play_store_512.png"
  adaptive_icon_foreground: "assets/launcher/play_store_512.png"
  adaptive_icon_background: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/drawer_icons/
    - assets/launcher/
    - assets/
    - assets/splash_screen_icons/
    - assets/error_images/
    - assets/home_images/
    - assets/login_images/
